# Generated by Django 3.1.4 on 2021-01-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=15)),
                ('l_name', models.CharField(max_length=15)),
                ('usr_name', models.CharField(max_length=15, unique=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
