# Generated by Django 3.2 on 2021-05-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20210420_2129'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='student',
        ),
        migrations.AlterModelTable(
            name='reg',
            table='login',
        ),
    ]
