# Generated by Django 3.1.4 on 2021-01-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='f_name',
            new_name='pwd',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='l_name',
        ),
    ]
