# Generated by Django 3.1.4 on 2021-02-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_auto_20210120_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='pwd',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
